name: Cancel GitHub Action

on:
  workflow_dispatch:
    inputs:
      workflow_id:
        description: 'GitHub Action Workflow ID'
        required: true

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: ${{ github.event.inputs.workflow_id }}
